### ISSUE TITLE
Controller freezes and kube fails to restart based on liveness.

### ISSUE THREAD

**Issue by alewitt2** [razee-io/Kubernetes-util#167]
**Describe the bug**
there are rare instances where we have seen our controller stop doing any work and there are no logs for several days, but kube hasnt restarted the pod. We are not quite sure why the liveness check dont cause our pod to be restarted, but have 1 theory that maybe we are touching the liveness file but not actually getting events from kube for some unknown reason.

ref:
- https://github.com/razee-io/Kubernetes-util/blob/master/lib/EventHandler.js#L56-L65
- https://github.com/razee-io/Kubernetes-util/blob/master/lib/Watchman.js#L63-L65
- https://github.com/razee-io/RemoteResource/blob/master/src/index.js#L33

**To Reproduce**
its intermittently rare and hard to reproduce

**Expected behavior**
kube should restart us based on our liveness or we should restart ourselves.

**Possible Solution**
we know that our watch gets recreated on an interval defined by [timeoutSeconds](https://github.com/razee-io/RemoteResource/blob/master/src/index.js#L33), so we should track when we start watching in watchman.js, and if we havent recieved any data or the connection hasnt closed in (timeoutSeconds + a few buffer minutes), then we should either restart the watch within the code or just exit the process and get restarted in a new container.

**Comment by alewitt2** [comment]
https://github.com/razee-io/Razee/issues/135

**Comment by charlesthomas** [comment]
we've encountered this and noticed that when it happens, the logs have not been updated. what if you changed `sh/liveness.sh` to watch a log file instead of a separate file?

**Comment by alewitt2** [comment]
thats a pretty good idea. we dont currently have a log file set up, but i imagine it wouldnt be too hard and should be for certain a good way to tell if we are still running or not.
